# Generated by Django 4.1.4 on 2022-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='grade',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('DE', 'Denmark')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerGrade',
        ),
    ]
