# Generated by Django 4.1.4 on 2022-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_nationality_alter_customer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
